[package]
name = "smw-gfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flexi_logger = "0.30.1"
image = "0.25.5"
log = "0.4.27"
